name: schoolparser
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
- python>=3.6
- pip=20
- mkl
- numpy>=1.14
- scipy>=1.1.0
- scikit-learn>=0.19.2
- pandas>=0.23.4
- joblib>=0.14
- matplotlib
- seaborn
- click
- natsort
- xlrd
- tqdm
- pybv
- pip:
  - pybids>=0.10
  - pydmd>=0.2.1

